# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Role.create(name: "admin")
Role.create(name: "manager")
Role.create(name: "staff")
Role.create(name: "accountant")


User.create(email: "can.ozel@bil.omu.edu.tr", password: "12345678")
User.create(email: "slhcnzl@gmail.com", password: "12345678")

Profile.create( user_id: 1, first_name: "Salih Can", last_name: "ÖZEL", date_of_birth: "14.04.1994",
                score: "10", gender: "Erkek", phone: "5434774173")
Profile.create( user_id: 2, first_name: "Semih", last_name: "ÖZEL", date_of_birth: "08.05.1998",
                score: "46", gender: "Erkek", phone: "5434774173")

User.first.add_role "admin"

Customer.create(first_name: "Yasin", last_name: "Erdem", location: "(40.613952441166596, 34.95849609375)",
                adress: "Cumhuriyet Mah. Lozan Cad. Anadolu Apt. D/Blok 13/5 Atakum İLKADIM / SAMSUN 
Türkiye 55200", phone: "5432134673")
Customer.create(first_name: "Yunus Emre", last_name: "Taşcıoğlu", location: "(40.623952441166596, 34.95849609375)",
                adress: "Cumhuriyet Mah. Lozan Cad. Anadolu Apt. D/Blok 13/5 Atakum İLKADIM / SAMSUN 
Türkiye 55200", phone: "5432134673")

Mission.create(user_id: 1, customer_id: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 1, customer_id: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 1, customer_id: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 1, customer_id: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 1, customer_id: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 1, customer_id: 1, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
Mission.create(user_id: 2, customer_id: 2, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed arcu nec justo tristique tempor a eleifend erat. Donec aliquet non leo sed tempor. Ut suscipit viverra bibendum. Praesent malesuada quam id eros consectetur euismod. Phasellus eu ornare lacus. Nunc quam ligula, vestibulum eu condimentum sed, tempor vitae ex. Pellentesque sed pulvinar magna. Quisque faucibus, tortor ac condimentum euismod, lorem turpis imperdiet leo, eget laoreet nunc odio vitae urna. Pellentesque laoreet et risus ut sodales. Nullam faucibus diam sed tellus tincidunt sollicitudin. Phasellus nec eros vitae lacus mollis aliquet.", state: true)
